Account for patches to previous major versions

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -4,8 +4,10 @@ on:
   workflow_dispatch:
     inputs:
       version:
-        description: The release version in <Major>.<minor> format
-        default: master
+        description: |
+          The release version in <Major>.<minor> format.
+          0.0 means new minor version on the latest major version.
+        default: '0.0'
         type: string
       dry-run:
         description: Do not push anything
@@ -14,7 +16,7 @@ on:
 
 jobs:
   release:
-    runs-on: ubuntu-24.04
+    runs-on: ubuntu-22.04
 
     steps:
       - uses: actions/checkout@v4
@@ -22,13 +24,26 @@ jobs:
           submodules: false
           fetch-depth: 0
 
+      - name: Parse required release
+        id: required-release
+        run: |
+          if [[ "${{ inputs.version }}" =~ ^([[:digit:]]+)\.([[:digit:]]+)$ ]]; then
+            echo "major=${BASH_REMATCH[1]}" >> "$GITHUB_OUTPUT"
+            echo "minor=${BASH_REMATCH[2]}" >> "$GITHUB_OUTPUT"
+          else
+            echo >&2 "Invalid version ${{ inputs.version }}"
+            exit 1
+          fi
+
       - name: Get closest tag to master
         id: latest-tag
+        env:
+          REQUIRED_MAJOR: ${{ steps.required-release.outputs.major }}
         run: |
           tag=(0 0)
           while read -r line; do
-            if [[ "$line" =~ ([[:digit:]]+)\.([[:digit:]]+)\.x ]]; then
-                if ((tag[0] < BASH_REMATCH[1])); then
+            if [[ "$line" =~ ^([[:digit:]]+)\.([[:digit:]]+)\.x$ ]]; then
+                if ((tag[0] < BASH_REMATCH[1] && (REQUIRED_MAJOR == 0 || REQUIRED_MAJOR >= BASH_REMATCH[1]))); then
                     tag=("${BASH_REMATCH[1]}" "${BASH_REMATCH[2]}")
                 elif ((tag[0] == BASH_REMATCH[1] && tag[1] < BASH_REMATCH[2])); then
                     tag=("${BASH_REMATCH[1]}" "${BASH_REMATCH[2]}")
@@ -40,10 +55,12 @@ jobs:
           echo "minor=${tag[1]}" >> "$GITHUB_OUTPUT"
 
       - name: Parse required release
-        id: required-release
+        id: final-values
         env:
-          MAJOR: ${{ steps.latest-tag.outputs.major }}
-          MINOR: ${{ steps.latest-tag.outputs.minor }}
+          LATEST_MAJOR: ${{ steps.latest-tag.outputs.major }}
+          LATEST_MINOR: ${{ steps.latest-tag.outputs.minor }}
+          REQUIRED_MAJOR: ${{ steps.required-release.outputs.major }}
+          REQUIRED_MINOR: ${{ steps.required-release.outputs.minor }}
         run: |
           function add_outputs() {
             cat << EOF >> "$GITHUB_OUTPUT"
@@ -53,86 +70,54 @@ jobs:
           EOF
           }
 
-          if [[ "${{ inputs.version }}" == "master" ]]; then
-            add_outputs "${MAJOR}" "$((MINOR+1))" "minor"
-          elif [[ "${{ inputs.version }}" =~ ([[:digit:]]+)\.([[:digit:]]+) ]]; then
-            if ((BASH_REMATCH[1] > MAJOR)); then
-              add_outputs "$((MAJOR+1))" "0" "major"
-            elif ((BASH_REMATCH[2] > MINOR)); then
-              add_outputs "${MAJOR}" "$((MINOR+1))" "minor"
-            else
-              add_outputs "${MAJOR}" "${BASH_REMATCH[2]}" "patch"
-            fi
+          if ((REQUIRED_MAJOR==0)); then
+            add_outputs "${LATEST_MAJOR}" "$((LATEST_MINOR+1))" "minor"
           else
-            echo >&2 "Invalid version ${{ inputs.version }}"
-            exit 1
+            if ((REQUIRED_MAJOR > LATEST_MAJOR)); then
+              add_outputs "$((LATEST_MAJOR+1))" "0" "major"
+            elif ((REQUIRED_MAJOR == LATEST_MAJOR && REQUIRED_MINOR > LATEST_MINOR)); then
+              add_outputs "${LATEST_MAJOR}" "$((LATEST_MINOR+1))" "minor"
+            else
+              add_outputs "${REQUIRED_MAJOR}" "${REQUIRED_MINOR}" "patch"
+            fi
           fi
 
       - name: Get patch version
         id: patch-version
-        if: steps.required-release.outputs.type == 'patch'
+        if: steps.final-values.outputs.type == 'patch'
         env:
-          MAJOR: ${{ steps.required-release.outputs.major }}
-          MINOR: ${{ steps.required-release.outputs.minor }}
+          MAJOR: ${{ steps.final-values.outputs.major }}
+          MINOR: ${{ steps.final-values.outputs.minor }}
         run: |
-          if [[ "${{ inputs.version }}" =~ ([[:digit:]]+)\.([[:digit:]]+) ]]; then
-            git checkout "release-${BASH_REMATCH[1]}.${BASH_REMATCH[2]}"
-            git pull --ff-only
+          git checkout "release-${MAJOR}.${MINOR}"
+          git pull --ff-only
 
-            patch=0
-            while read -r line; do
-              if [[ "$line" =~ ${MAJOR}.${MINOR}.([[:digit:]]+) ]]; then
-                if ((BASH_REMATCH[1] > patch)); then
-                  patch="${BASH_REMATCH[1]}"
-                fi
+          patch=0
+          while read -r line; do
+            if [[ "$line" =~ ^${MAJOR}.${MINOR}.([[:digit:]]+)$ ]]; then
+              if ((BASH_REMATCH[1] > patch)); then
+                patch="${BASH_REMATCH[1]}"
               fi
-            done < <(git tag --merged)
-          else
-            echo >&2 "Invalid version input '${{ inputs.version }}'"
-            exit 1
-          fi
+            fi
+          done < <(git tag --merged)
 
           echo "value=$((patch+1))" >> "$GITHUB_OUTPUT"
 
-      - name: Set variables
-        id: variables
+      - name: Notify tags and branches
         env:
-          REQUIRED_MAJOR: ${{ steps.required-release.outputs.major }}
-          REQUIRED_MINOR: ${{ steps.required-release.outputs.minor }}
-          REQUIRED_PATCH: ${{ steps.patch-version.outputs.value || '0' }}
-          RELEASE_TYPE: ${{ steps.required-release.outputs.type }}
+          MAJOR: ${{ steps.final-values.outputs.major }}
+          MINOR: ${{ steps.final-values.outputs.minor }}
+          PATCH: ${{ steps.patch-version.outputs.value || '0' }}
+          RELEASE_TYPE: ${{ steps.final-values.outputs.type }}
         run: |
-          case "$RELEASE_TYPE" in
-            major)
-              MAJOR=${REQUIRED_MAJOR}
-              MINOR=0
-              PATCH=0
-              BRANCH=master
-            ;;
-
-            minor)
-              MAJOR=${REQUIRED_MAJOR}
-              MINOR=${REQUIRED_MINOR}
-              PATCH=0
-              BRANCH=master
-            ;;
-
-            patch)
-              MAJOR=${REQUIRED_MAJOR}
-              MINOR=${REQUIRED_MINOR}
-              PATCH=${REQUIRED_PATCH}
-              BRANCH=release-${MAJOR}.${MINOR}
-            ;;
-
-            *)
-              echo >&2 "Invalid release type '$RELEASE_TYPE'"
-              exit 1
-            ;;
-          esac
-
           function notice() {
             echo "::notice title=$1:: $2"
           }
+
+          BRANCH="master"
+          if [[ "${RELEASE_TYPE}" == "${PATCH}" ]]; then
+            BRANCH="release-${MAJOR}.${MINOR}"
+          fi
 
           notice "Release type" "${RELEASE_TYPE}"
           notice "Tag" "${MAJOR}.${MINOR}.${PATCH}"
@@ -142,22 +127,15 @@ jobs:
             notice "Release branch" "release-${MAJOR}.${MINOR}"
           fi
 
-              cat << EOF >> "$GITHUB_OUTPUT"
-          major=${MAJOR}
-          minor=${MINOR}
-          patch=${PATCH}
-          branch=${BRANCH}
-          EOF
-
       - name: Initialize mandatory git config
         run: |
           git config user.name "${{ github.event.sender.login }}"
           git config user.email noreply@github.com
 
       - name: Create release branch
-        if: steps.variables.outputs.branch == 'master'
+        if: steps.final-values.outputs.type != 'patch'
         env:
-          RELEASE: ${{ steps.variables.outputs.major }}.${{ steps.variables.outputs.minor }}
+          RELEASE: ${{ steps.final-values.outputs.major }}.${{ steps.final-values.outputs.minor }}
         run: |
           git checkout master
           git pull --ff-only
@@ -166,18 +144,18 @@ jobs:
           git commit --no-verify --allow-empty -m "Empty commit to diverge ${RELEASE} from master"
 
       - name: Push release branch
-        if: steps.variables.outputs.branch == 'master' && !inputs.dry-run
+        if: steps.final-values.outputs.type != 'patch' && !inputs.dry-run
         env:
-          RELEASE: ${{ steps.variables.outputs.major }}.${{ steps.variables.outputs.minor }}
+          RELEASE: ${{ steps.final-values.outputs.major }}.${{ steps.final-values.outputs.minor }}
         run: |
           git push origin "${RELEASE}.x"
           git push --set-upstream origin "release-${RELEASE}"
 
       - name: Create release tag
         env:
-          RELEASE: ${{ steps.variables.outputs.major }}.${{ steps.variables.outputs.minor }}
+          RELEASE: ${{ steps.final-values.outputs.major }}.${{ steps.final-values.outputs.minor }}
           RELEASE_TYPE: ${{ steps.required-release.outputs.type }}
-          PATCH: ${{ steps.variables.outputs.patch }}
+          PATCH: ${{ steps.patch-version.outputs.value || '0' }}
         run: |
           git checkout "release-${RELEASE}"
           if [[ "${RELEASE_TYPE}" == "patch" ]]; then
@@ -188,15 +166,15 @@ jobs:
       - name: Push release tag
         if: ${{ !inputs.dry-run }}
         env:
-          RELEASE: ${{ steps.variables.outputs.major }}.${{ steps.variables.outputs.minor }}
-          PATCH: ${{ steps.variables.outputs.patch }}
+          RELEASE: ${{ steps.final-values.outputs.major }}.${{ steps.final-values.outputs.minor }}
+          PATCH: ${{ steps.patch-version.outputs.value || '0' }}
         run: |
           git push origin "${RELEASE}.${PATCH}"
 
 #      - name: Create tag in falcosecurity-libs
 #        env:
 #          RELEASE: ${{ steps.variables.outputs.major }}.${{ steps.variables.outputs.minor }}
-#          PATCH: ${{ steps.variables.outputs.patch }}
+#          PATCH: ${{ steps.patch-version.outputs.value || '0' }}
 #        run: |
 #          git submodule update --init falcosecurity-libs
 #          cd falcosecurity-libs/
@@ -206,7 +184,7 @@ jobs:
 #        if: ${{ !inputs.dry-run }}
 #        env:
 #          RELEASE: ${{ steps.variables.outputs.major }}.${{ steps.variables.outputs.minor }}
-#          PATCH: ${{ steps.variables.outputs.patch }}
+#          PATCH: ${{ steps.patch-version.outputs.value || '0' }}
 #        run: |
 #          cd falcosecurity-libs/
 #          git push origin "${RELEASE}.${PATCH}"
